--DROP TABLE TBL_PRODUCTO;
--DROP TABLE TBL_PROVEEDOR;
--DROP TABLE TBL_DESTINO;
--DROP TABLE TBL_USUARIO_AUTHORITY;
--DROP TABLE TBL_USUARIO;
--DROP TABLE TBL_AUTHORITY;

--DROP SEQUENCE SEQ_PRODUCTO;
--DROP SEQUENCE SEQ_PROVEEDOR;
--DROP SEQUENCE SEQ_DESTINO;
--DROP SEQUENCE SEQ_USUARIO;
--DROP SEQUENCE SEQ_AUTHORITY;
--DROP SEQUENCE SEQ_USUARIO_AUTHORITY;

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE TABLE TBL_PROVEEDOR(
    PROVEEDOR_ID NUMERIC(7) NOT NULL PRIMARY KEY,
    RUC VARCHAR2 (20) NOT NULL UNIQUE, 
	RAZON_SOCIAL VARCHAR2(150) NOT NULL UNIQUE,
    MOVIL VARCHAR2(15) NOT NULL, 
	EMAIL VARCHAR2(100) NOT NULL, 
	REPRESENTANTE_LEGAL VARCHAR2(150) NOT NULL,
    ESTADO CHAR(1) DEFAULT '1' NOT NULL
);

CREATE TABLE TBL_DESTINO(
    DESTINO_ID NUMERIC(1) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(240) NOT NULL UNIQUE,
    ESTADO CHAR(1) DEFAULT '1' NOT NULL
);

CREATE TABLE TBL_PRODUCTO(
    PRODUCTO_ID NUMERIC(6) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(240) NOT NULL UNIQUE,
    PRECIO NUMERIC(6,2) NOT NULL,
    STOCK NUMERIC(6,2) NOT NULL,
    COD_EAN VARCHAR2(13),
    TIENDA NUMERIC(1) NOT NULL,
    PROVEEDOR_ID NUMERIC(7) REFERENCES TBL_PROVEEDOR(PROVEEDOR_ID),
    DESTINO_ID NUMERIC(1) REFERENCES TBL_DESTINO(DESTINO_ID),
    ESTADO CHAR(1) DEFAULT '1' NOT NULL
);

CREATE TABLE TBL_USUARIO 
   (USUARIO_ID NUMBER(4,0) NOT NULL PRIMARY KEY, 
	USUARIO VARCHAR2(20 BYTE) NOT NULL UNIQUE, 
	CLAVE VARCHAR2(80 BYTE) NOT NULL , 
	NOMBRE VARCHAR2(120 BYTE)NOT NULL,
	ESTADO CHAR(1 BYTE) DEFAULT 1 NOT NULL
    );

CREATE TABLE TBL_AUTHORITY 
   (AUTHORITY_ID NUMBER(4,0) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR2(120 BYTE)NOT NULL,
	ESTADO CHAR(1 BYTE) DEFAULT 1 NOT NULL
    );
CREATE TABLE TBL_USUARIO_AUTHORITY 
   (USUARIO_AUTHORITY_ID NUMBER(4,0) NOT NULL PRIMARY KEY,
	USUARIO_ID NUMBER(4,0) NOT NULL REFERENCES TBL_USUARIO(USUARIO_ID),
    AUTHORITY_ID NUMBER(4,0) NOT NULL REFERENCES TBL_AUTHORITY(AUTHORITY_ID),
	ESTADO CHAR(1 BYTE) DEFAULT 1 NOT NULL
    );

CREATE SEQUENCE SEQ_PRODUCTO;
CREATE SEQUENCE SEQ_PROVEEDOR;
CREATE SEQUENCE SEQ_DESTINO;
CREATE SEQUENCE SEQ_USUARIO;
CREATE SEQUENCE SEQ_AUTHORITY;
CREATE SEQUENCE SEQ_USUARIO_AUTHORITY;

INSERT INTO TBL_PROVEEDOR(PROVEEDOR_ID,RUC,RAZON_SOCIAL,MOVIL,EMAIL,REPRESENTANTE_LEGAL,ESTADO) VALUES (SEQ_PROVEEDOR.NEXTVAL, '11235645647','EL MACHO','611235645','ROJASUAP@GMAIL.COM','PEDRO ROJAS ENCISO','1');
INSERT INTO TBL_PROVEEDOR(PROVEEDOR_ID,RUC,RAZON_SOCIAL,MOVIL,EMAIL,REPRESENTANTE_LEGAL,ESTADO) VALUES (SEQ_PROVEEDOR.NEXTVAL, '11335645698','LA PASIEGA','630235698','CISNEROT@GMAIL.COM','TANIA CISNERO','1');

INSERT INTO TBL_DESTINO(DESTINO_ID,NOMBRE) VALUES (SEQ_DESTINO.NEXTVAL, 'DESTINO TIENDAS MERCADONA ESPAÑA');
INSERT INTO TBL_DESTINO(DESTINO_ID,NOMBRE) VALUES (SEQ_DESTINO.NEXTVAL, 'DESTINO TIENDAS MERCADONA PORTUGAL');
INSERT INTO TBL_DESTINO(DESTINO_ID,NOMBRE) VALUES (SEQ_DESTINO.NEXTVAL, 'ALMACENES');
INSERT INTO TBL_DESTINO(DESTINO_ID,NOMBRE) VALUES (SEQ_DESTINO.NEXTVAL, 'OFICINAS MERCADONA');
INSERT INTO TBL_DESTINO(DESTINO_ID,NOMBRE) VALUES (SEQ_DESTINO.NEXTVAL, 'MERCADONA');

INSERT INTO TBL_PRODUCTO(PRODUCTO_ID,NOMBRE,PRECIO,STOCK,COD_EAN,TIENDA,PROVEEDOR_ID,DESTINO_ID) VALUES (SEQ_PRODUCTO.NEXTVAL, 'Producto 1',2000.0,10.0,'0000001000011',1,1,1);
INSERT INTO TBL_PRODUCTO(PRODUCTO_ID,NOMBRE,PRECIO,STOCK,COD_EAN,TIENDA,PROVEEDOR_ID,DESTINO_ID) VALUES (SEQ_PRODUCTO.NEXTVAL, 'Producto 2',4000.0,10.0,'0000002000011',2,1,1);
INSERT INTO TBL_PRODUCTO(PRODUCTO_ID,NOMBRE,PRECIO,STOCK,COD_EAN,TIENDA,PROVEEDOR_ID,DESTINO_ID) VALUES (SEQ_PRODUCTO.NEXTVAL, 'Producto 3',5000.0,10.0,'0000003000011',3,1,1);
INSERT INTO TBL_PRODUCTO(PRODUCTO_ID,NOMBRE,PRECIO,STOCK,COD_EAN,TIENDA,PROVEEDOR_ID,DESTINO_ID) VALUES (SEQ_PRODUCTO.NEXTVAL, 'Producto 4',6000.0,10.0,'0000004000011',4,1,1);
INSERT INTO TBL_PRODUCTO(PRODUCTO_ID,NOMBRE,PRECIO,STOCK,COD_EAN,TIENDA,PROVEEDOR_ID,DESTINO_ID) VALUES (SEQ_PRODUCTO.NEXTVAL, 'Producto 5',7000.0,10.0,'0000005000011',5,2,1);
INSERT INTO TBL_PRODUCTO(PRODUCTO_ID,NOMBRE,PRECIO,STOCK,COD_EAN,TIENDA,PROVEEDOR_ID,DESTINO_ID) VALUES (SEQ_PRODUCTO.NEXTVAL, 'Producto 6',8000.0,10.0,'0000006000011',6,2,2);
INSERT INTO TBL_PRODUCTO(PRODUCTO_ID,NOMBRE,PRECIO,STOCK,COD_EAN,TIENDA,PROVEEDOR_ID,DESTINO_ID) VALUES (SEQ_PRODUCTO.NEXTVAL, 'Producto 7',9000.0,10.0,'0000007000011',8,2,3);

INSERT INTO TBL_USUARIO(USUARIO_ID ,USUARIO,CLAVE,NOMBRE)
VALUES(SEQ_USUARIO.NEXTVAL,'ADMIN','$2a$10$birg4J.F9cr96ViWFVNLsO/Sj/YT0uue2PtvQd2U5mp.cJDk7dHyS','ADMINISTRADOR');
 INSERT INTO TBL_USUARIO(USUARIO_ID ,USUARIO,CLAVE,NOMBRE)
VALUES(SEQ_USUARIO.NEXTVAL,'DEMO','$2a$10$birg4J.F9cr96ViWFVNLsO/Sj/YT0uue2PtvQd2U5mp.cJDk7dHyS','DEMO');

INSERT INTO TBL_AUTHORITY(AUTHORITY_ID,NOMBRE)
VALUES(SEQ_AUTHORITY.NEXTVAL,'ROLE_ADMIN');  

INSERT INTO TBL_AUTHORITY(AUTHORITY_ID,NOMBRE)
VALUES(SEQ_AUTHORITY.NEXTVAL,'ROLE_USER');

INSERT INTO TBL_USUARIO_AUTHORITY(USUARIO_AUTHORITY_ID,USUARIO_ID,AUTHORITY_ID)
VALUES(SEQ_USUARIO_AUTHORITY.NEXTVAL,1,1);  
INSERT INTO TBL_USUARIO_AUTHORITY(USUARIO_AUTHORITY_ID,USUARIO_ID,AUTHORITY_ID)
VALUES(SEQ_USUARIO_AUTHORITY.NEXTVAL,1,2);  
INSERT INTO TBL_USUARIO_AUTHORITY(USUARIO_AUTHORITY_ID,USUARIO_ID,AUTHORITY_ID)
VALUES(SEQ_USUARIO_AUTHORITY.NEXTVAL,2,2); 

COMMIT;